### ISSUE TITLE
What does the charWhiteList do?

### ISSUE THREAD

**Issue by RVijay007** [BlinkOCR/blinkocr-ios#11]
I'm checking out the sample apps, but am unclear what the char white list is doing. The OCR results are still showing other characters besides what is specified in the char white list, such as the receipt demo showing characters like `(`,  `)`, `,`. How would I be able to filter only for alphanumeric characters and bias the results to picking on the white listed characters?

**Comment by Pickles112358** [comment]
Hello,

This is indeed a bug in the SDK. We will fix it asap. Thank you for the report!

Kind regards,
Dino

**Comment by Pickles112358** [comment]
This error has just been fixed with the new version. However, you can no longer read current options. Instead, you need to create new options and set them.

Let me know if i can help you with anything else
