### ISSUE TITLE
BlinkId framework, will it support for Single line MRZ code readability?

### ISSUE THREAD

**Issue by nrvraghu** [BlinkOCR/blinkocr-ios#14]
I have been using your frame for OCR and blink Id, I would like use this framework to read single line MRZ code, will it support? If it can, where can I get the latest code for this?

**Comment by Pickles112358** [comment]
Hello,

Currently, scanning a single line from MRZ is not supported but if MRZ is a single line (such as US cheques), this is on our roadmap. We would love to hear about your specific use case at info@microblink.com
Ideally, you could send us a picture of which document you are trying to scan.

Kind regards,
Dino

**Comment by nrvraghu** [comment]
Thanks for your kind information.
