### ISSUE TITLE
MRZ code reading too quick in landscape and giving the invalid values?

### ISSUE THREAD

**Issue by nrvraghu** [BlinkOCR/blinkocr-ios#15]
Hi Blink Team, 
  I am being using the this framework, "setAllowUnparsedResults:YES" I had given this into PPMrtdRecognizerSettings,  when the app in my device, if it's in portrait the MRZ code is reading after the camera seeing the MRZ properly, when it's in land scape it is too quicker than the portrait capturing time and giving the "isParsed = false" and different values too. 
Please assist me on this. 
Thanks in advance!

**Comment by Cerovec** [comment]
Hi - this is expected. Enabling allowUnparsedResults will disable all parsing checks (such as checksums) which are performed internally in the SDK.
If you need more reliable results, you can implement additional verification that 2 or 3 times you received the same OCR results.
If you experience fast scans, then you have enough processing time to spare for this additional checks.
Does this sound reasonable for you?

**Comment by nrvraghu** [comment]
Hi,
I have verified this many times and yet i am not able to find it reasonable as you say. I have clearly mentioned this problem arises only in the landscape mode and not in the portrait mode. i scan a passport in portrait mode and  it gets detected as a valid passport and if i try the same in landscape mode it gets invalid checksum! This doesn't make any sense.  **"I cannot even position the camera onto the passport - Which means i cannot get the passport scanned. The landscape scanning is done too fast which does not even allow me to position the camera and doesn't lets the camera to focus onto the passport which is not the case in portrait mode. "**

**Comment by Cerovec** [comment]
Hi,

thanks for the more detailed description. We'll definitely investigate why this happens.

In the meantime, can you share with us the reason why you use allowUnparsedResults=true?
If you have any issues with parsing some ID documents, you can report it as another issue so we can fix it.

Using internal parsing has many advantages, the most important one is that checksum validation and parsing significantly improves the OCR results, and lowers the error rate. 

When parsing is enabled, we also verify that all scanned ID cards follow the ISO/IEC 7501 standard.

**Comment by nrvraghu** [comment]
Hi,
The allowUnparsedResults=true is used to end any parsing that is done on any invalid passport. Without this we will not be able to skip the parsing for invalid passports, which also means that the scanning goes on and on without getting terminated.  

Also I wanted to point out that this issue which we are discussing happens in landscape mode and also happens in both Android and iOS platforms.

**Comment by Cerovec** [comment]
Hi,
can you implement the following inside the scanning callback.

Obtain the OCR result.
If the OCR result is the first one ever, store it as lastOcrResult and continue scanning
If the OCR result is not the first one, compare it with lastOcrResult. If they are the same, use this result and stop the scanning process. If they are not, store it as lastOcrResult and continue scanning.

In that way you will not experience the problems you're referring to.

Kind regards,
Jurica.

**Comment by nrvraghu** [comment]
Hi,
Obtain the OCR result.
If the OCR result is the first one ever, store it as lastOcrResult and continue scanning
If the OCR result is not the first one, compare it with lastOcrResult. If they are the same, use this result and stop the scanning process. If they are not, store it as lastOcrResult and continue scanning.

The logic looks good, but I will not be able to validate the passport wether it is fake or not. because, in the landscape mode, the camera is not getting positioned properly to parse the data which is the major concern. without having this data i can not store in last OCR result which will also not allow me to identify fake passport.

**Comment by Cerovec** [comment]
If you implement the logic above, you won't have issues with positioning. Because, you won't stop the scanning process if two OCR results are not the same! 

Please let us know when you implemented the logic above (it's 10-15 lines of code).
