### ISSUE TITLE
Swift 3 Compatibility

### ISSUE THREAD

**Issue by ABCode9** [BlinkOCR/blinkocr-ios#18]
I've installed the latest PPBlinkOcr Podfile into my Swift 3 project, but it doesn't seem to be compatible with Swift 3 language. I can build and run the simulator fine with the sample app provided, which is great, but I don't know how to implement the code into my own Swift 3 project. Am I missing something?

**Comment by Pickles112358** [comment]
Samples included with our latest release should not work correctly with Swift 3.
