### ISSUE TITLE
BlinkOCR can NOT coexist with BlinkID

### ISSUE THREAD

**Issue by juliangsp** [BlinkOCR/blinkocr-ios#4]
BlinkOCR SDK can NOT coexist in the same project/workspace with BlinkID SDK. I'm downloading both SDKs via Cocoapods. The **PPCoordinator** class on both SDKs are different and the BlinkOCR is recognized first in Xcode over the BlinkID.

**Comment by Cerovec** [comment]
This is expected. Both frameworks cannot work together, due to shared classes (linker will complain with duplicate symbol errors).

The best solution is to **use BlinkID** framework, which has the same features as BlinkOCR, and more.

**Comment by juliangsp** [comment]
Thanks! I got it working as said. As a reference I used in the Podfile
`pod 'PPBlinkID', :git => 'https://github.com/blinkid/blinkid-ios', :branch => 'feature/blinkocr'`
but I had to install first **git lfs**.

**Comment by Cerovec** [comment]
Hi Julian,
yes, unfortunately because of Bitcode support and Github's file size limit of 100MB, **git lfs** will be required with new versions of our SDKs. But we believe this is a better solution than dropping bitcode support.
Let us know if you need any other help!
