### ISSUE TITLE
Bit Code support

### ISSUE THREAD

**Issue by ivan-ushakov** [BlinkOCR/blinkocr-ios#5]
Hello,

I'm getting this error with current framework version:

    MicroBlink.embeddedframework/MicroBlink.framework/MicroBlink' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

Is it ok and I should disable bit code in my project? I just don't see this step in documentation. If yes, do you have any estimation when you add bit code support?

**Comment by Pickles112358** [comment]
Hello,

Thank you for the error report, we certainly forgot to add that step to our Getting started guide. Yes, for now you need to disable bitcode in your project. Our next release, which will come soon (this month hopefully) will contain bitcode support.

**Comment by Cerovec** [comment]
Hi Ivan,
current release supports bitcode. Can you double check if everything works for you?
Kind regards,
Jurica.

**Comment by ivan-ushakov** [comment]
Hi,

I'm having problems with updating SDK to current version. First of all you changed API (some class names, interfaces) and documentation was not updated. This could confuse user. 

Second problem is linking. I'm getting this error:

       ld: warning: ignoring file /MyApp/MicroBlink.framework/MicroBlink, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): /MyApp/MicroBlink.framework/MicroBlink
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_PPOverlayViewController", referenced from:
          
      "_OBJC_CLASS_$_PPSettings", referenced from:
          
      "_OBJC_CLASS_$_PPCoordinator", referenced from:
          
      "_OBJC_CLASS_$_PPRawOcrParserFactory", referenced from:
          
      "_OBJC_CLASS_$_PPRecognizerResult", referenced from:
          
      "_OBJC_CLASS_$_PPZXingRecognizerSettings", referenced from:
          
      "_OBJC_CLASS_$_PPBlinkOcrRecognizerSettings", referenced from:
          
      "_OBJC_METACLASS_$_PPOverlayViewController", referenced from:
          
      "_OBJC_CLASS_$_PPZXingRecognizerResult", referenced from:
          
      "_OBJC_CLASS_$_PPBlinkOcrRecognizerResult", referenced from:
          
    ld: symbol(s) not found for architecture arm64

**Comment by Pickles112358** [comment]
Hello,

For transitioning into new version please read our transition guide (available here: https://github.com/BlinkOCR/blinkocr-ios/blob/master/Transition%20guide.md).
As for the error, it is probably related to Git LFS. Please install Git LFS (available here: https://git-lfs.github.com) so you can clone our repository correctly.
Let us know if you need any more help!

Kind regards,
Dino

**Comment by ivan-ushakov** [comment]
Yes, sorry about LFS. Linking works now. And bitcode works too.

**Comment by bhaveshr970** [comment]
ld: warning: ignoring file /MyApp/MicroBlink.framework/MicroBlink, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): /MyApp/MicroBlink.framework/MicroBlink
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PPOverlayViewController", referenced from:

  "_OBJC_CLASS_$_PPSettings", referenced from:

  "_OBJC_CLASS_$_PPCoordinator", referenced from:

  "_OBJC_CLASS_$_PPRawOcrParserFactory", referenced from:

  "_OBJC_CLASS_$_PPRecognizerResult", referenced from:

  "_OBJC_CLASS_$_PPZXingRecognizerSettings", referenced from:

  "_OBJC_CLASS_$_PPBlinkOcrRecognizerSettings", referenced from:

  "_OBJC_METACLASS_$_PPOverlayViewController", referenced from:

  "_OBJC_CLASS_$_PPZXingRecognizerResult", referenced from:

  "_OBJC_CLASS_$_PPBlinkOcrRecognizerResult", referenced from:

ld: symbol(s) not found for architecture arm64

How to resolve it. As I am using XCode 7.3.1
Please let me know

**Comment by rezasham** [comment]
Hi, I´m getting the exact same issue as bhaveshr970 reported above. Should we open up a new issue? I just downloaded and try to compile the swift version on my phone, but getting this issue wich actually causes 9 other errors and thus not able to run the code to test.

Thanks,

R

**Comment by rezasham** [comment]
Actually, seems like the issue is gone in the latest release. The problem exist if you try to download probably an older version through a link somewhere referring to "Download", probably want to update wherer this link is pointing.

Reza
