### ISSUE TITLE
No Results in NoCamera-sample

### ISSUE THREAD

**Issue by sha8wn** [BlinkOCR/blinkocr-ios#6]
I was just running the NoCamera-sample project out of the box as it is. The only change I made was to the api key so that it would run. It just shows a UIAlertView with the text No result. 

I can see in the logs it says: "Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates."

Not sure what I need to do here to make this sample work.

**Comment by Cerovec** [comment]
Hi Sha8wn,

no results means the OCR engine for some reason didn't manage to find any relevant text on the image. It's usually caused by nonoptimal OCR parameteres.

Can you please send us a photo of the document you're trying to OCR? We would need it too recreate and analyse the issue.
