### ISSUE TITLE
BlinkOCR for swift example

### ISSUE THREAD

**Issue by hprobotic** [BlinkOCR/blinkocr-ios#8]
When i try to download and run blink ocr example in swift version. This response so many error.
Can you give working version of this or add BlinkOCR started guid via swift

**Comment by Cerovec** [comment]
Hi,
since travis build is passing, we don't believe we have issues with the sample itself.
Please try installing git lfs.
If this still doesn't help, please copy here the exact compile errors.
Kind regards,
Jurica.

**Comment by altinselimi** [comment]
Here are some:

![image](https://cloud.githubusercontent.com/assets/10469822/18818577/373462a8-837d-11e6-8508-2fa382db008a.png)
