### ISSUE TITLE
Get warning and then a whole bunch of linker errors when I try to build any of the sample projects ... HELP!

### ISSUE THREAD

**Issue by tomadoran** [BlinkOCR/blinkocr-ios#9]
Hi There,

I'm getting a warning then a whole bunch of linker errors when I try to build any of the sample projects, I'm using XCode Version 7.3.1 (7D1014).

The error is listed below.

Thanks,
Tom.

===============

warning: ignoring file ../../MicroBlink.framework/MicroBlink, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): ../../MicroBlink.framework/MicroBlink
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PPBlinkOcrRecognizerResult", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPBlinkOcrRecognizerSettings", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPCoordinator", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPOcrCharKey", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPRawOcrParserFactory", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPSettings", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Cerovec** [comment]
Hi Tom,

since travis build is passing, which indicates that everything is OK with the library itself, my guess is that you don't have git large file storage installed.

Please follow the instrallation instructions from here: https://git-lfs.github.com

If this is correct, the real issue we have is that this is not mentioned in the documentation. :/

Kind regards,
Jurica.

**Comment by tomadoran** [comment]
Thanks Jurica, yes let me give that a try and I'll get back to you.

Tom.

**Comment by tomadoran** [comment]
Hi Jurica,

I have installed the Git LFS successfully, however I still get the same
error when trying to build any of the sample apps. Is there some config I
have to do between Xcode and this GIT LFS? This seems to be the missing
link. Since when Xcode is building it does not seem to be aware that the
BlinkOCR Framework Exec file is actually a remote file.

Please let me know, since this is very frustrating, this should ideally
work out of the box, and not have these hoops to jump through. I followed
you documentation step by step and it still does not work.

Thanks,
Tom.

**Comment by tomadoran** [comment]
Also, when I terminal into the BlinkOCR framework, there's a MicroBlink
file in there, I tried to run this and got this error:

LM-SJL-00874627:MicroBlink.framework tdoran$ ./MicroBlink

./MicroBlink: line 1: version: command not found

./MicroBlink: line 2: oid: command not found

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/size:
118283264: No such file or directory.

LM-SJL-00874627:MicroBlink.framework tdoran$ ./MicroBlink

**Comment by tomadoran** [comment]
ok I got a little further, I installed CocoaPods, which the documentation
states as optional, however looks like required. I followed the steps, but
got this the odd message below, which I thin is because I downloaded the
BlinkOCR and Not the BlinkID ... dude your documentation needs a little
improvement :-) I'm going to edit this pod file to be "PPBlinkOCR" to see
if this will work!

LM-SJL-00874627:Receipt-sample tdoran$ pod install

Setting up CocoaPods master repo

Setup completed

Analyzing dependencies

[!] The dependency `PPBlinkID (from `
https://github.com/blinkocr/blinkocr-ios`, branch `master`)` is not used in
any concrete target.

**Comment by tomadoran** [comment]
ok your Podfile does not work for the BlinkOCR samples, it may work for the
BlinkID, however I'm not interested in this, I want BlinkOCR :-)

SO this

platform :ios, '7.0'
pod 'PPBlinkID', :git => 'https://github.com/blinkocr/blinkocr-ios',
:branch => 'master'

Does NOT work for your BlinkOCR samples,

**Comment by tomadoran** [comment]
Your Podfile does not work for your BlinkOCR samples, since I think it's
for the BlinkID samples. So you need to update it for the BlinkOCR.

platform :ios, '7.0'
pod 'PPBlinkID', :git => 'https://github.com/blinkocr/blinkocr-ios',
:branch => 'master'

**Comment by tomadoran** [comment]
I get this issue below, with no "<blah>.xcworkspace" generated, PLEASE HELP!

/Users/tdoran/blinkocr-ios-feature-v1.2.0/Samples/Receipt-sample

LM-SJL-00874627:Receipt-sample tdoran$ ls -l

total 8

drwxr-xr-x@ 14 tdoran  100006119  476 May 31 07:41 MicroBlink.bundle

drwxr-xr-x@  6 tdoran  100006119  204 May 31 07:41 MicroBlink.framework

-rw-r--r--   1 tdoran  100006119  111 Jun 20 20:05 Podfile

drwxr-xr-x   6 tdoran  100006119  204 Jun 20 20:05 Pods

drwxr-xr-x@ 10 tdoran  100006119  340 May 31 07:41 Receipt-sample

drwxr-xr-x@  6 tdoran  100006119  204 Jun 20 19:25 Receipt-sample.xcodeproj

LM-SJL-00874627:Receipt-sample tdoran$ pod install

Analyzing dependencies

[!] The dependency `PPBlinkID (from `
https://github.com/blinkocr/blinkocr-ios`, branch `master`)` is not used in
any concrete target.

LM-SJL-00874627:Receipt-sample tdoran$

**Comment by tomadoran** [comment]
I'm trying to get the Blink OCR Swift sample working in Xcode, I've tried
all sorts of Hacks, I think the issue is that the use of CocoaPods for the
Framework dependencies mapping is complete broken.

Have you actually tried to get this building in Xcode itself? It is
completely broken!

Thanks,
Tom.

**Comment by Pickles112358** [comment]
Hello tomadoran,

Our framework file is stored in Git LFS which means it wont be pulled when you clone the repository unless you have Git LFS installed. Did you try cloning our repository after you installed Git LFS?

Also thank you for the error report with podspec.

Please let me know if you managed to clone the repository successfuly the second time.

Kind regards,
Dino

**Comment by Pickles112358** [comment]
Alright, thanks for the error reports, the documentation for installing Git LFS has been updated because of it.
If you need any more help with our SDK don't hesitate ask!

Kind regards,
Dino
